# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: [ubuntu-latest]
    env:
      DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ vars.DOCKER_PASSWORD }}
    steps:
      - name: Read a variable docker username
        run: echo "My docker_username value is $DOCKER_USERNAME"
      - name: Read a variable docker password
        run: echo "My docker_password value is $DOCKER_PASSWORD"
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to docker hub
        run: docker login -u ${{ vars.DOCKER_USERNAME }} -p ${{ vars.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t nes224/nodejscicd .
      - name: Publish image to docker hub
        run: docker push nes224/nodejscicd:latest
  
  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull image from docker hub
        run: docker pull nes224/nodejscicd:latest
      - name: Delete old container
        run: docker rm -f nodejs-app-container
      - name: Run docker container
        run: docker run -d -p 5000:5000 --name nodejs-app-container nes224/nodejscicd


             
