# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "cicd-docker-ec2" ]

jobs:
  build:
    runs-on: [ubuntu-latest]
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWOR }}
    steps:
      - name: Read a variable docker username
        run: echo "My docker_username value is $DOCKER_USERNAME"
      - name: Read a variable docker password
        run: echo "My docker_password value is $DOCKER_PASSWORD"
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t integrationninjas/nodejs-app .
      - name: Publish image to docker hub
        run: docker push integrationninjas/nodejs-app:latest


             
